### ISSUE TITLE
Ternary breaks theming

### ISSUE THREAD

**Issue by noon92** [swindex/leet-html#1]
First extension I've seen that "just works" for proper highlighting of css and html. One issue: 
The following line of JS causes the rest of the document to have html theming. However, if I switch it from a ternary to an if statement, the issue is fixed.

`        document.getElementById("apP2h").innerHTML = !apS.br ? `<svg height=\"60\" width=\"165\" fill=\"#${apS.col.tc2}\" stroke=\"#${apS.col.tc2}\" alt=\"A11yPro ${fc.logo}\"><use xlink:href=\"#aplogo\"><\/svg>` : apV.lang.t.info; //replace a11ypro logo with "More info" if nobranding is active`

![image](https://user-images.githubusercontent.com/40807970/234957661-899f8bfa-0b3d-471b-8e47-a17b47e58cf4.png)

**Comment by noon92** [comment]
Correction: it appears that the issue is the escaped `/` in the `<\/svg>`. When I remove the escaping, it works as expected. when the \/ is present, the theming for the rest of the code breaks.

**Comment by swindex** [comment]
Hi,
There is a limitation in what kinds of patterns VSCode can recognize, so when something isn't highlighted, use the ```/*html*/``` comment right before the template.

Your issue is because VSCode's HTML parser does not consider your templated code valid and thus breaks the rest of the file.
You can remedy the issue by enclosing the offending template in round braces like this:
```(`<div>This is invalid html<\/div>`)```
See more examples here.
(the round brace fix on lines 35 and 36)
![image](https://user-images.githubusercontent.com/31745189/235038085-c7599bc3-8942-48b4-8600-0a846fcfadb9.png)

**Comment by noon92** [comment]
Thank you! I appreciate it. Great project!
